---
driver_config:
  openstack_username: <%= ENV['OPENSTACK_USERNAME'] %>
  openstack_api_key: <%= ENV['OPENSTACK_API_KEY'] %>
  openstack_auth_url: <%= ENV['OPENSTACK_AUTH_URL'] %>
  key_name: <%= ENV['KEY_NAME'] %>
  private_key_path: <%= ENV['PRIVATE_KEY_PATH'] %>
  floating_ip_pool: nova
  flavor_ref: mt.bigmed
  image_ref: Ubuntu Server 14.04 - RAW
  server_name: bamboo-int
transport:
  ssh_key: <%= ENV['PRIVATE_KEY_PATH'] %>
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu
  disable_ssl_validation: true

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-14.04
  driver_plugin: openstack
  run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[bamboo]
    attributes:
      bamboo:
        name: bamboo-dev
        backup:
          enabled: false
          ceph: false
        agent:
          data_dir: /var/bamboo-agent
          home_dir: /opt/bamboo-agent
